spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: WenYiJun@0223
    url: jdbc:mysql://gz-cynosdbmysql-grp-ey8wvxrr.sql.tencentcdb.com:28076/jiakao?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver